package SAGA.events;

public enum EventType {
    ORDER_CREATED,
    ORDER_CREATE_FAILED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    INVENTORY_RESERVED,
    INVENTORY_FAILED,
    ORDER_CANCELLED,
    ORDER_CONFIRMED
}
